console.log(typeof 1);
console.log(typeof typeof 1);
console.log(typeof (()=>{}));
console.log(typeof function(){});
console.log(typeof NaN);
console.log('a' + 100);
console.log('a' * 100);
console.log('123' + 1);
console.log('123' * 1);
console.log(100 / 0);
console.log(typeof (100 / 0));
console.log(typeof undefined);
console.log(typeof null);
console.log(typeof {});
console.log(typeof []);